// <auto-generated />
namespace Attendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Addingthemodelsandaddingcreatingtheusercontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingthemodelsandaddingcreatingtheusercontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "202501280708006_Adding the models and adding creating the user controller "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
