// <auto-generated />
namespace Attendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mergeMigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergeMigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202502040744128_mergeMigrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
