// <auto-generated />
namespace Attendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addedlogindto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedlogindto));
        
        string IMigrationMetadata.Id
        {
            get { return "202502031001186_added login dto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
